version: '3.8'
services:
  client:
    build:
      context: ./client
      target: production
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=http://api.yourdomain.com
    depends_on:
      - server

  server:
    build:
      context: ./server
      target: production
    command: npm start
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskflow
      - CLIENT_URL=http://yourdomain.com
      - JWT_SECRET=${JWT_SECRET}
      - CSRF_SECRET=${CSRF_SECRET}
      - PORT=3000
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=taskflow
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data

volumes:
  postgres_prod_data:
